---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mariadb
  namespace: test
  labels:
    chart: mariadb
spec:
  chartGitPath: mariadb
  values:
    mariadb:
      image: bitnami/mariadb:10.1-ol-7
    persistence:
      enabled: false
