---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: maria.db
  namespace: test
  labels:
    chart: mariadb
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chartGitPath: mariadb
  values:
    mariadb:
      image: bitnami/mariadb:10.1-debian-9
    sidecar:
      image: weaveworks/sidecar:0.1
    persistence:
      enabled: false
