---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mongodb
  namespace: test
  labels:
    chart: mongodb
  annotations:
    flux.weave.works/automated: 'true'
spec:
  chartGitPath: mongodb
  releaseName: mongodb-database
  values:
    image: bitnami/mongodb:4-debian-8-master
    imagePullPolicy: IfNotPresent
    persistence:
      enabled: false
